### ISSUE TITLE
Install dependencies and devdependencies

### ISSUE THREAD

**Issue by dannyfritz** [noseglid/atom-build-npm-apm#18]
When i run `npm install` on my terminal, `npm` installs `dependencies` and `devDependecies`.

When I run `npm install` through this package, it only installs `dependencies`. Can we either get it to install `devDependencies` also or get a configuration for it?

**Comment by dannyfritz** [comment]
Poked a little further in the `npm help install` help file. Very likely related to this:

```
           By default, npm install will install all modules listed  as  depen-
         dencies
           in npm help 5 package.json.
           With  the --production flag (or when the NODE_ENV environment vari-
         able
           is set to production), npm will not install modules listed in
           devDependencies.
```

`production` is probably what Atom is running under.

**Comment by noseglid** [comment]
Hmm, I think the reason is because atom runs with `NODE_ENV=production` (which sets the same options as `--production` flag). All tough this is quite speculatory from my side.

Does it work if you start atom from the command line with `NODE_ENV=development atom` or something equivalent if you're on windows? I'm not sure how to set environment for windows applications...

**Comment by dannyfritz** [comment]
This was happening on my OSX machine, which I won't be on again until Monday. I suspect running Atom with `-d` or `--dev` will make it install the `devDependencies` as Atom does indeed run under `production` mode most of the time. Can be confirmed by opening the JS Console in Atom and typing `process.env.NODE_ENV`

**Comment by noseglid** [comment]
Hmm, I wonder if this package should unset `NODE_ENV` so it's independent of what Atom has.  What do you think?

I really hate that it's inheriting that environment.

**Comment by ldrick** [comment]
I had to change this line:
```javascript
const env = {FORCE_COLOR: '1', MOCHA_COLORS: '1', NPM_CONFIG_COLOR: 'always'};
```
to this:
```javascript
const env = {FORCE_COLOR: '1', MOCHA_COLORS: '1', NPM_CONFIG_COLOR: 'always', NODE_ENV: ''};
```
Otherwise all my dev-dependencies were purged.
But configuration would be the best solution for my team.
