### ISSUE TITLE
Configure path to package.json

### ISSUE THREAD

**Issue by bsrdjan** [noseglid/atom-build-npm-apm#23]
When `package.json` not located in the project root folder, the builder does not find the `package.json` .

How to tell the build system the directory where `package.json` is located, when not in the project root folder ?

**Comment by noseglid** [comment]
It can't.
Could you describe your working environment?

**Comment by bsrdjan** [comment]
It is web application development, with the server (`/www`) and client (`/application`) in the same project:

``` shell
├── LICENSE
├── README.md
├── VERSION
├── application
│   ├── Makefile
│   ├── README.md
│   ├── build
│   ├── config
│   ├── fonts
│   ├── images
│   ├── index.html
│   ├── jsconfig.json
│   ├── node_modules
│   ├── package.json
│   ├── sass
│   ├── src
│   ├── styles
│   ├── test
│   └── webpack.config.js
└── www
    ├── README.md
    ├── dist
    ├── requirements.txt
    ├── serve.py
    ├── serve.sh
    └── utils.py
```

During development, the client is served locally and for deployment it is bundled and packaged into `www/dist` folder, then published to web server. All done by npm tasks.

In my current editor the path to package.json is configurable and I try to achieve the same with Atom.

**Comment by bsrdjan** [comment]
Solved
