### ISSUE TITLE
Specify in README that “engines” field is needed

### ISSUE THREAD

**Issue by flying-sheep** [noseglid/atom-build-npm-apm#8]
this did nothing until i looked in the code and i found that you need the `engines` field in `package.json`.

i think more people are confused since this is the first time i heard of this field.

**Comment by noseglid** [comment]
Ah yea... it's to distinguish between `apm` and `npm`. I think the best solution to this would be to default to `npm` since that is hands-down more used than `apm`. Thanks for reporting this!

**Comment by raoel** [comment]
For other people who are having the same problem, add the following configuration option to package.json:

``` json
"engines": {
    "node": "*",
    "atom": "*"
  }
```

**Comment by TigersWay** [comment]
Maybe time to consider other package manager, like pnpm or yarn, with the right 'engines' set of course.
